clean:
  convert_nan_to_str:
    colname: artist
  convert_str_to_datetime:
    colname: releaseyear
    format: "%B %d %Y"
  approximate_missing_year:
    fill_column: releaseyear
    approximate_with: reviewdate
  convert_datetime_to_date:
    colname: releaseyear
  fill_missing_manually:
    colname: recordlabel
  strip_whitespace:
    colname: recordlabel
  bucket_values_together:
    iteration1:
      colname: recordlabel
      values:
        - Maybach Music Group
        - Maybach/Warner Bros.
      replace_with: Maybach
    iteration2:
      colname: recordlabel
        values:
          - Self
          - none
        replace_with: Self-released
  fill_na_with_str_missing:
    colname: genre
    fill_string: Missing
model:
  split_train_val_test:
    train_val_test_ratio: "6:2:2"
    random_state: 3947
  make_model:
    learning_rate: 0.075
    ccp_alpha: 0.001
    random_state: 3947
  make_preprocessor:
    numeric_features:
      - releaseyear
      - danceability
      - key
      - loudness
      - speechiness
      - acousticness
      - instrumentalness
      - liveness
      - valence
      - tempo
    categorical_features:
      - genre
    handle_unknown: ignore
